name: 'Setup Node.js'
description: 'Sets up Node.js and npm cache'

inputs:
  node-version:
    description: 'Version of Node.js to use (e.g. 20, 22)'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
