name: 'Pack NuGet Package'
description: 'Packs a .NET project as a NuGet package and uploads it as an artifact'

inputs:
  dotnet-project:
    description: 'Path to a .NET project (.csproj) or solution (.sln/.slnx) file to pack'
    required: false
    default: '**/*.{sln,slnx}'
  configuration:
    description: 'Build configuration (e.g. Debug or Release)'
    required: false
    default: 'Release'
  version:
    description: 'Version to use for the NuGet package (e.g. 1.2.3)'
    required: true

runs:
  using: 'composite'
  steps:
      - name: Pack NuGet package
        shell: bash
        run: |
          shopt -s globstar nullglob
          dotnet pack ${{ inputs.dotnet-project }} \
            --configuration ${{ inputs.configuration }} \
            --output ./nupkgs \
            --no-build \
            /p:PackageVersion=${{ inputs.version }}

      - name: Upload nupkgs artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkgs
          path: ./nupkgs/*.nupkg
          if-no-files-found: error
